export const cities = [
  { id: 1, name: 'Aitape' },
  { id: 2, name: 'Alotau' },
  { id: 3, name: 'Arawa' },
  { id: 4, name: 'Bulolo' },
  { id: 5, name: 'Daru' },
  { id: 6, name: 'Goroka' },
  { id: 7, name: 'Ialibu' },
  { id: 8, name: 'Kainantu' },
  { id: 9, name: 'Kavieng' },
  { id: 10, name: 'Kerema' },
  { id: 11, name: 'Kimbe' },
  { id: 12, name: 'Kiunga' },
  { id: 13, name: 'Kokopo' },
  { id: 14, name: 'Kundiawa' },
  { id: 15, name: 'Lae' },
  { id: 16, name: 'Lorengau' },
  { id: 17, name: 'Madang' },
  { id: 18, name: 'Mendi' },
  { id: 19, name: 'Mount Hagen' },
  { id: 20, name: 'Popondetta' },
  { id: 21, name: 'Port Moresby' },
  { id: 22, name: 'Rabaul' },
  { id: 23, name: 'Tabubil' },
  { id: 24, name: 'Tari' },
  { id: 25, name: 'Vanimo' },
  { id: 26, name: 'Wabag' },
  { id: 27, name: 'Wau' },
  { id: 28, name: 'Wewak' },
  { id: 29, name: 'Manus' },
];

export const provinces = [
  { id: 1, name: 'Central' },
  { id: 2, name: 'Chimbu (Simbu)' },
  { id: 3, name: 'East New Britain' },
  { id: 4, name: 'East Sepik' },
  { id: 5, name: 'Eastern Highlands' },
  { id: 6, name: 'Enga' },
  { id: 7, name: 'Gulf' },
  { id: 8, name: 'Hela' },
  { id: 9, name: 'Jiwaka' },
  { id: 10, name: 'Madang' },
  { id: 11, name: 'Manus' },
  { id: 12, name: 'Milne Bay' },
  { id: 13, name: 'Morobe' },
  { id: 14, name: 'National Capital District' },
  { id: 15, name: 'New Ireland' },
  { id: 16, name: 'Northern (Oro)' },
  { id: 17, name: 'Southern Highlands' },
  { id: 18, name: 'Western (Fly)' },
  { id: 19, name: 'Western Highlands' },
  { id: 20, name: 'West New Britain' },
  { id: 21, name: 'West Sepik (Sandaun)' },
  { id: 22, name: 'Autonomous Region of Bougainville' },
];

export const country = [{ id: 1, name: 'Papua New Guinea' }];

export const address = [
  {
    id: 1,
    address1: 'Western',
    address2: 'Jiwaka',
    city: 'Manus',
    province: 'Morobe',
    country: 'Papua New Guinea',
  },
];
