export { default as UsersIconRound } from './user';
export { default as MultiFactorIcon } from './multi-factor';
export { default as SmsCodeIcon } from './sms-code';
export { default as EmailIcon } from './email';
export { default as VerificationIcon } from './verification-icon';
export { default as CollapseIcon } from './collapse';
export { default as AdminDashboardIcon } from './admin-dashboard';
export { default as UserManagementIcon } from './user-management';
export { default as SecuritySettingsIcon } from './secuity-settings';
export { default as LogManagementIcon } from './log-management';
export { default as NotificationsIcon } from './notifications';
export { default as LogoutIcon } from './logout';
export { default as CollapseCloseIcon } from './collapse-close';
export { default as UserManagementDashboardIcon } from './user-management-dashboard';
export { default as SortingIcon } from './sorting';
export { default as LicenseMaintenanceIcon } from './license-maintenance';
export { default as LegalDocumentIcon } from './legal-document';
export { default as UserSettingsIcon } from './user-settings';
export { default as UserTimeIcon } from './user-time';
export { default as AccountTypeIcon } from './account-type';
export { default as RoleIcon } from './role';
export { default as DivisionIcon } from './division';
export { default as UnitIcon } from './unit';
export { default as EditDivisionIcon } from './edit-division';
export { default as EditLoginMethodIcon } from './edit-login-method';
export { default as UnitLeftPanelIcon } from './unit-left-panel';
export { default as EditUnitIcon } from './edit-unit';
export { default as HeaderUnitIcon } from './header-unit';
export { default as EditMultiAuthIcon } from './edit-multi-auth';
export { default as PhoneIcon } from './phone';
export { default as AccountStatusIcon } from './account-status';
export { default as FileIcon } from './file';
export { default as AddIcon } from './add-icon';
export { default as EditPasswordIcon } from './edit-password';
export { default as EditPreferLoginMethodIcon } from './edit-prefer-login-method';
export { default as EditCreateDateIcon } from './edit-create-date';
export { default as EditChangeDateIcon } from './edit-change-date';
export { default as EditTrashIcon } from './edit-trash';
export { default as LockKeyIcon } from './lock-key';
export { default as SquareLockIcon } from './square-lock';
export { default as CheckMarkCircle } from './check-mark-circle';
export { default as UnlinkIcon } from './unlink';
export { default as MessageLockIcon } from './message-lock';
export { default as BackIcon } from './back';
export { default as AccountSettingIcon } from './account-setting';
export { default as Switch } from './switch';
export { default as Sort } from './sort-by';
export { default as DownloadCircleIcon } from './download-circle';
export { default as ViewIcon } from './view';
export { default as EditIcon } from './edit';
export { default as ExchangeIcon } from './exchange';
export { default as FileSyncIcon } from './file-sync';
export { default as FileUnknownIcon } from './file-unknown';
export { default as PencilEditIcon } from './pencil-edit';
export { default as AccessIcon } from './access';
export { default as PdfIcon } from './pdf';
export { default as FileAttachmentIcon } from './file-attachment';
export { default as ApplicationSubmissionPDFIcon } from './application-submission-pdf';
export { default as ApplicationSubmissionDownloadPDFIcon } from './application-submission-download-pdf';
export { default as BuildingIcon } from './building-05';
export { default as RoadLocationIcon } from './road-location';
export { default as AuditIcon } from './audit';
export { default as MapLocationIcon } from './map-location';
export { default as MapsSquareIcon } from './maps-square';
export { default as NavigationIcon } from './navigation';
export { default as PdfShowIcon } from './pdf-show';
export { default as EarthIcon } from './earth';
export { default as PassportIcon } from './passport';
export { default as Verification } from './view-notification';

import type { SVGProps } from 'react';

export type SVG = {
  svgProps?: SVGProps<SVGSVGElement>;
  pathProps?: SVGProps<SVGPathElement>;
};
