import type { ViewApplicationDetail } from '../types/api';

export const mockData: ViewApplicationDetail = {
  additional_information: 'This corporation has additional information for regulatory review.',
  additional_supporting_document_ids: [101],
  additional_supporting_documents: [
    {
      capital_market_representative_license_holder_id: 12,
      corporation_applicant_id: 45,
      created_at: '2025-06-01T09:30:00Z',
      document: 'https://www.antennahouse.com/hubfs/xsl-fo-sample/pdf/basic-link-1.pdf',
      id: 101,
      individual_applicant_id: 0,
      name: 'Company Charter Document',
      updated_at: '2025-06-10T10:00:00Z',
    },
  ],
  address_of_branch_where_business_is_conducted_city: 'Jakarta',
  address_of_branch_where_business_is_conducted_country: 'Indonesia',
  address_of_branch_where_business_is_conducted_line1: 'Jl. Jend. Sudirman No. 1',
  address_of_branch_where_business_is_conducted_line2: 'Gedung A, Lantai 5',
  address_of_branch_where_business_is_conducted_postal_code: '10210',
  address_of_branch_where_business_is_conducted_province: 'DKI Jakarta',
  business_name: 'PT Teknologi Canggih',
  contact_first_name: 'Agus',
  contact_middle_name: 'Setia',
  contact_surname: 'Wibowo',
  created_at: '2025-05-01T08:00:00Z',
  director_ids: [201],
  directors: [
    {
      corporation_applicant_id: 45,
      created_at: '2025-05-01T08:00:00Z',
      first_name: 'Dewi',
      id: 201,
      middle_name: 'Kartika',
      surname: 'Putri',
      updated_at: '2025-06-01T09:00:00Z',
    },
  ],
  email_for_service: 'legal@pttekcanggih.co.id',
  id: 45,
  ipa_extract_document: 'https://www.antennahouse.com/hubfs/xsl-fo-sample/pdf/basic-link-1.pdf',
  ipa_extract_document_uploaded_at: '2025-06-02T12:30:00Z',
  ipa_registration_number: 'IPA-2025-123456',
  license_application_id: 3001,
  license_application_ids: [3001],
  name: 'PT Teknologi Canggih',
  phone_for_service: '+62-21-555-1234',
  physical_address_of_principle_place_of_business_city: 'Bandung',
  physical_address_of_principle_place_of_business_country: 'Indonesia',
  physical_address_of_principle_place_of_business_line1: 'Jl. Asia Afrika No. 99',
  physical_address_of_principle_place_of_business_line2: 'Komplek Perkantoran Bumi',
  physical_address_of_principle_place_of_business_postal_code: '40111',
  physical_address_of_principle_place_of_business_province: 'Jawa Barat',
  preferred_address_of_service: 'physical_address_of_principle_place_of_business',
  secretaries: [
    {
      corporation_applicant_id: 45,
      created_at: '2025-05-01T08:30:00Z',
      first_name: 'Budi',
      id: 301,
      middle_name: 'Santoso',
      surname: 'Wijaya',
      updated_at: '2025-06-01T09:30:00Z',
    },
  ],
  secretary_ids: [301],
  shareholder_ids: [401],
  shareholders: [
    {
      capital_market_representative_license_holder_id: 12,
      corporation_applicant_id: 45,
      created_at: '2025-04-15T14:00:00Z',
      first_name: 'Linda',
      id: 401,
      middle_name: 'Maria',
      number_of_shares: 1000,
      surname: 'Sutanto',
      type_of_shares: 'Ordinary',
      updated_at: '2025-06-01T10:00:00Z',
    },
  ],
};
